import { useEffect, useState } from 'react';
import { ArrowRight, Box, Building2, FileBox, Search, ShieldCheck } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import ProductCard from '../components/mvp/ProductCard';
import { EmptyState, LoadingState } from '../components/mvp/States';
import { useLanguage } from '../context/LanguageContext';
import { mvpService } from '../services/mvpService';

export default function Home() {
  const { lang, t } = useLanguage(); const navigate = useNavigate();
  const [query, setQuery] = useState(''); const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([mvpService.getLatestProducts(8), mvpService.getCategories(), mvpService.getSuppliers({ limit: 4 })]).then(([p, c, s]) => { setProducts(p); setCategories(c); setSuppliers(s); }).catch(() => {}).finally(() => setLoading(false)); }, []);
  const submit = (event) => { event.preventDefault(); navigate(`/blocks${query ? `?q=${encodeURIComponent(query)}` : ''}`); };
  return <div className="bg-ivory"><section className="relative flex min-h-[760px] items-center overflow-hidden bg-deep-brown px-6 pb-24 pt-32 text-warm-white"><img src="/hero.jpg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-deep-brown via-deep-brown/90 to-dark-brown/25 rtl:bg-gradient-to-l"/><div className="relative mx-auto w-full max-w-7xl"><div className="max-w-3xl"><p className="mb-6 text-xs font-bold uppercase tracking-[.3em] text-gold">{t('Construction product data, built for design', 'بيانات منتجات البناء، مصممة للتصميم')}</p><h1 className="text-5xl font-black leading-[1.1] sm:text-6xl lg:text-7xl">{t('The professional construction product and BIM/3D block library.', 'مكتبة احترافية لمنتجات البناء وبلوكات BIM وثلاثية الأبعاد.')}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-sand/80">{t('Find reliable product information, technical specifications, supplier data and downloadable design files in one focused library.', 'اعثر على معلومات المنتجات والمواصفات الفنية وبيانات الموردين وملفات التصميم القابلة للتحميل في مكتبة واحدة مركزة.')}</p><form onSubmit={submit} className="mt-10 flex max-w-2xl flex-col gap-3 rounded-2xl bg-white/10 p-3 backdrop-blur sm:flex-row"><label className="relative flex-1"><span className="sr-only">{t('Search the library', 'البحث في المكتبة')}</span><Search className={`absolute top-1/2 -translate-y-1/2 text-light-brown ${lang === 'ar' ? 'right-4' : 'left-4'}`} size={20}/><input value={query} onChange={(e) => setQuery(e.target.value)} className={`h-14 w-full rounded-xl bg-warm-white text-dark-brown outline-none ring-gold focus:ring-2 ${lang === 'ar' ? 'pr-12 pl-4' : 'pl-12 pr-4'}`} placeholder={t('Search products, references or categories…', 'ابحث عن منتجات أو مراجع أو فئات…')}/></label><button className="btn-gold h-14 justify-center px-8">{t('Search blocks', 'ابحث في البلوكات')}<ArrowRight className={lang === 'ar' ? 'rotate-180' : ''} size={17}/></button></form></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-4 px-6 py-16 md:grid-cols-3">{[[FileBox,t('Structured product data', 'بيانات منتجات منظمة'),t('Names, descriptions, specifications and references.', 'أسماء وأوصاف ومواصفات ومراجع.')],[Box,t('BIM & 3D ready', 'جاهز لـ BIM وثلاثي الأبعاد'),t('Available design files with clear software details.', 'ملفات تصميم متاحة مع تفاصيل البرامج.')],[ShieldCheck,t('Secure access', 'وصول آمن'),t('Short-lived links protect downloadable product assets.', 'روابط قصيرة المدة لحماية ملفات المنتجات.')]].map(([Icon,title,desc]) => <div key={title} className="rounded-2xl border border-sand bg-white p-7"><Icon className="mb-5 text-gold"/><h2 className="font-bold text-dark-brown">{title}</h2><p className="mt-2 text-sm leading-6 text-light-brown">{desc}</p></div>)}</section>
    <section className="mx-auto max-w-7xl px-6 py-16"><SectionHeading eyebrow={t('Browse by discipline', 'تصفح حسب التخصص')} title={t('Product categories', 'فئات المنتجات')} link="/blocks" t={t}/>{categories.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.slice(0,8).map((category) => <Link key={category.id} to={`/blocks?category=${category.id}`} className="rounded-xl border border-sand bg-white p-5 font-bold text-dark-brown transition hover:border-gold"><span className="mr-3 text-gold">{category.icon || '◇'}</span>{lang === 'ar' ? category.name_ar : category.name_en}</Link>)}</div> : <EmptyState title={t('Categories will appear here', 'ستظهر الفئات هنا')}/>}</section>
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow={t('Recently published', 'أضيف حديثاً')} title={t('Latest blocks', 'أحدث البلوكات')} link="/blocks" t={t}/>{loading ? <LoadingState/> : products.length ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id || product.slug} product={product}/>)}</div> : <EmptyState title={t('No published blocks yet', 'لا توجد بلوكات منشورة حالياً')}/>}</div></section>
    <section className="mx-auto max-w-7xl px-6 py-20"><SectionHeading eyebrow={t('From the source', 'من المصدر')} title={t('Supplier windows', 'نوافذ الموردين')} link="/suppliers" t={t}/>{suppliers.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{suppliers.map((supplier) => <Link key={supplier.id || supplier.slug} to={`/suppliers/${supplier.slug}`} className="flex items-center gap-4 rounded-2xl border border-sand bg-white p-5 hover:border-gold"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-xl bg-ivory">{supplier.signed_logo_url ? <img src={supplier.signed_logo_url} alt="" className="h-full w-full object-contain"/> : <Building2 className="text-beige"/>}</div><strong className="text-dark-brown">{lang === 'ar' ? supplier.company_name_ar || supplier.name_ar : supplier.company_name_en || supplier.name_en}</strong></Link>)}</div> : <EmptyState title={t('Supplier windows will appear here', 'ستظهر نوافذ الموردين هنا')}/>}</section>
    <section className="bg-dark-brown px-6 py-20 text-center text-warm-white"><h2 className="text-3xl font-black">{t('Build your professional block library.', 'ابنِ مكتبتك الاحترافية من البلوكات.')}</h2><p className="mx-auto mt-4 max-w-xl text-sand/75">{t('Create a free account to access available BIM, 3D and datasheet downloads.', 'أنشئ حساباً مجانياً للوصول إلى ملفات BIM وثلاثية الأبعاد وملفات البيانات المتاحة.')}</p><Link to="/login" className="btn-gold mt-8">{t('Create account', 'إنشاء حساب')}<ArrowRight className={lang === 'ar' ? 'rotate-180' : ''} size={16}/></Link></section>
  </div>;
}

function SectionHeading({ eyebrow, title, link, t }) { return <div className="mb-9 flex items-end justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-gold">{eyebrow}</p><h2 className="text-3xl font-black text-dark-brown">{title}</h2></div><Link to={link} className="hidden items-center gap-2 text-sm font-bold text-gold sm:flex">{t('View all', 'عرض الكل')}<ArrowRight size={15}/></Link></div>; }
