import { useLanguage } from '../context/LanguageContext';

export default function Privacy() {
  const { t } = useLanguage();
  const sections = [
    [t('Information we process', 'المعلومات التي نعالجها'), t('BUOD processes account details such as name, email, user type, and optional company information. It also records limited platform events such as page views and file-download actions needed to operate and improve the service.', 'يعالج BUOD بيانات الحساب مثل الاسم والبريد الإلكتروني ونوع المستخدم ومعلومات الشركة الاختيارية. كما يسجل أحداثاً محدودة في المنصة مثل مشاهدات الصفحات وعمليات تنزيل الملفات اللازمة لتشغيل الخدمة وتحسينها.')],
    [t('Why we use it', 'لماذا نستخدمها'), t('We use this information to authenticate users, enforce permissions, provide requested content, protect the platform, and understand basic service usage.', 'نستخدم هذه المعلومات لمصادقة المستخدمين وتطبيق الصلاحيات وتقديم المحتوى المطلوب وحماية المنصة وفهم الاستخدام الأساسي للخدمة.')],
    [t('Service providers', 'مزودو الخدمة'), t('Authentication and database services are provided through Supabase, and the web application is hosted through Vercel. These providers process data only as needed to deliver their services.', 'تُقدَّم خدمات المصادقة وقاعدة البيانات عبر Supabase، وتُستضاف واجهة الويب عبر Vercel. يعالج هؤلاء المزودون البيانات بالقدر اللازم لتقديم خدماتهم.')],
    [t('Access and retention', 'الوصول والاحتفاظ'), t('Access is limited by account role and database security policies. Data is retained while needed for the staging evaluation, account administration, security, or applicable obligations.', 'يُقيَّد الوصول حسب دور الحساب وسياسات أمان قاعدة البيانات. تُحتفظ البيانات ما دامت لازمة لتقييم Staging أو إدارة الحساب أو الأمان أو الالتزامات المعمول بها.')],
    [t('Your choices', 'خياراتك'), t('You can request correction or deletion of your account data by contacting the BUOD platform administrator. Some records may be retained when required for security or legal obligations.', 'يمكنك طلب تصحيح بيانات حسابك أو حذفها بالتواصل مع مدير منصة BUOD. قد يُحتفظ ببعض السجلات عند الحاجة للأمان أو للالتزامات النظامية.')],
  ];
  return <div className="bg-ivory px-6 pb-20 pt-28"><article className="mx-auto max-w-3xl rounded-3xl border border-sand bg-white p-7 shadow-card sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">BUOD</p><h1 className="mt-3 text-3xl font-black text-dark-brown">{t('Privacy Policy', 'سياسة الخصوصية')}</h1><p className="mt-4 leading-7 text-light-brown">{t('This notice explains how the BUOD staging platform handles personal information.', 'يوضح هذا الإشعار كيفية تعامل منصة BUOD التجريبية مع المعلومات الشخصية.')}</p><p className="mt-2 text-xs text-light-brown">{t('Last updated: 17 August 2026', 'آخر تحديث: 17 أغسطس 2026')}</p><div className="mt-10 space-y-8">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-lg font-bold text-dark-brown">{heading}</h2><p className="mt-2 leading-7 text-medium-brown">{body}</p></section>)}</div></article></div>;
}
